export { Home } from './home-page/Home';
export { Login } from './login-page/Login';
export { Registration } from './register-page/Registration';
export { Account } from './account-page/Account';
export { Collection } from './collection-page/Collection';
export { Item } from './item-page/Item';
export { Admin } from './admin-page/Admin';
export { SearchResult } from './search-page/SearchResult';
export { NotFound } from './notfound-page/NotFound';