export const userActionTypes = {
  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "FETCH_USER_ERROR",
};

export const collectionActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_ERROR: "FETCH_COLLECTIONS_ERROR",
  FETCH_BIGCOLLECTIONS_START: "FETCH_BIGCOLLECTIONS_START",
  FETCH_BIGCOLLECTIONS_SUCCESS: "FETCH_BIGCOLLECTIONS_SUCCESS",
  FETCH_BIGCOLLECTIONS_ERROR: "FETCH_BIGCOLLECTIONS_ERROR",
  DELETE_START: "DELETE_START",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_ERROR: "DELETE_ERROR",
  FETCH_VALUE_FOR_EDIT_START: "FETCH_VALUE_FOR_EDIT_START",
  FETCH_VALUE_FOR_EDIT_SUCCESS: "FETCH_VALUE_FOR_EDIT_SUCCESS",
  FETCH_VALUE_FOR_EDIT_ERROR: "FETCH_VALUE_FOR_EDIT_ERROR",
  CREATE_COLLECTION_START: "CREATE_COLLECTION_START",
  CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
  UPDATE_COLLECTION_SUCCESS: "UPDATE_COLLECTION_SUCCESS",
  CLOSE_FORM: "CLOSE_FORM"
};